/*

*/

#ifndef Vitality_DEFINES_H
#define Vitality_DEFINES_H

enum VitalitySpellIds
{
    SPELL_HUNGER_THRIVING = 800000,
    SPELL_HUNGER_WELL_FED = 800001,
    SPELL_HUNGER_HUNGRY = 800002,
    SPELL_HUNGER_STARVING = 800003,
};

constexpr uint32 VITALITY_TRIGGER_FLAGS =
    TRIGGERED_INSTANT_CAST |
    TRIGGERED_IGNORE_GCD |
    TRIGGERED_IGNORE_COSTS |
    TRIGGERED_IGNORE_COOLDOWNS |
    TRIGGERED_IGNORE_CURRENT_CASTED_SPELL;

#endif